import os, django

from connections.mongodb import MongoDbConn

from config_vars import DOC_ELEMENTS_COLLECTION, DOCUMENTS_COLLECTION, MAPPING_COLLECTION, TEMPLATE_COLLECTION
os.environ['DJANGO_SETTINGS_MODULE'] = 'console.settings'
django.setup()
import pytest


temp = {
    "solution_id" : "aranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7",
    "template_id" : "a629ac584-7afe-43c6-935c-507d76632dd3",
    "is_draft" : True,
    "doc_processing_state" : "hocr",
    "template_type" : "known",
    "pages" : [
        {
            "file_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/pages/7dfd171a-b5a6-4f25-b884-05a392b61d4b-1.png",
            "text_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/hocr/7dfd171a-b5a6-4f25-b884-05a392b61d4b-1.txt",
            "hocr_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/hocr/7dfd171a-b5a6-4f25-b884-05a392b61d4b-1.hocr",
            "page_no" : 1,
            "keywords" : [
                "U",
                "1a",
                "no",
                "02",
                "LAS7",
                "4o",
                "IOIiIdI",
                "St",
                "IrMemcaremI",
                "Midde",
                "Stranglove",
                "Last",
                "12",
                "LUNG",
                "PROGRAM",
                "IYES",
                "muccorg",
                "4",
                "TELEPHONE",
                "Emulate",
                "NPI",
                "tenems",
                "Seiix",
                "made",
                "or",
                "AUTHORIZED",
                "ACCIDENT",
                "Holmes",
                "5551212",
                "PLEASE",
                "FLIlBEDF",
                "Indude",
                "Regent",
                "ACCOUNT",
                "04",
                "IDJ",
                "SVBEI",
                "Q",
                "CODES",
                "DE",
                "c",
                "DESIgnated",
                "PERSON",
                "ORIGINAL",
                "Id",
                "APPROVED",
                "To",
                "Kip",
                "D",
                "A",
                "l1",
                "r",
                "statements",
                "SDATE",
                "claim",
                "t",
                "Middle",
                "q",
                "III",
                "YI",
                "K",
                "Informaan",
                "F",
                "l_l",
                "CH",
                "JL",
                "an",
                "PLAN",
                "It",
                "16",
                "AMOUNT",
                "I_J",
                "TO",
                "MNO",
                "paymem",
                "FIISI",
                "desolmo",
                "NUMBER",
                "PERSONS",
                "Relate",
                "30",
                "FORM",
                "below",
                "FCFI",
                "IE",
                "thereof",
                "Manual",
                "QUALI",
                "Code",
                "02f12",
                "Results",
                "MYES",
                "M1Mi",
                "IVES",
                "I_i",
                "QUAL",
                "25",
                "are",
                "lAI",
                "TYPE",
                "2",
                "Use",
                "IUdV",
                "NATIONAL",
                "Ynl",
                "FRCM",
                "12I25I16I12I25I16I11I",
                "USE",
                "AUTO",
                "N",
                "RELATED",
                "PHYSICIAN",
                "REF",
                "INSUREDIS",
                "I_l",
                "magma",
                "THERE",
                "myself",
                "CREDENTIALS",
                "www",
                "CA",
                "NUCCJ",
                "H",
                "party",
                "21",
                "1212",
                "TOTAL",
                "serums",
                "LCDATICN",
                "FACILITY",
                "BENEFIT",
                "DATES",
                "Signature",
                "ADDRESS",
                "IniIlal",
                "10",
                "9",
                "payment",
                "0r",
                "CF",
                "rl",
                "OCCUPATION",
                "ANOTHER",
                "MM",
                "UNIFORM",
                "SP",
                "l",
                "First",
                "11",
                "MEDICAID",
                "FEDERALTAX",
                "3376535030",
                "Feme",
                "BY",
                "No",
                "DAVS",
                "Fl",
                "GROJP",
                "lfyes",
                "Insetme",
                "on",
                "READ",
                "AVL",
                "to",
                "Ihe",
                "I_INO",
                "OR",
                "CHARGE",
                "MEDICARE",
                "PATIENTS",
                "PRCERAM",
                "SIGNATURE",
                "IS",
                "items",
                "EMG",
                "assignment",
                "7900",
                "Unusual",
                "J",
                "CPTIHCPCS",
                "53",
                "6",
                "SE",
                "FROM",
                "SERVICES",
                "SERVICE",
                "555",
                "SIGNED",
                "DD",
                "umlM",
                "CLAIM",
                "COMMHTEE",
                "O",
                "31",
                "CR",
                "23",
                "mygluan",
                "OtherI",
                "DA",
                "INCLUDING",
                "INSURANCE",
                "1770638030",
                "Flsvcltor",
                "0",
                "and",
                "1",
                "r03",
                "IL",
                "II",
                "a",
                "PLACE",
                "medical",
                "p",
                "release",
                "REFERRING",
                "STATE",
                "IXI",
                "Instruction",
                "YY",
                "State",
                "Main",
                "01719",
                "22",
                "RENDERING",
                "INSURANu",
                "For",
                "CUTSI",
                "MIMI",
                "123",
                "5",
                "r_l",
                "G",
                "Dr",
                "Name",
                "0ng",
                "process",
                "Memberle",
                "El",
                "7",
                "NO",
                "z",
                "94704",
                "DUI",
                "ool",
                "RAID",
                "EMPLOYMENT",
                "CHARGES",
                "In",
                "Omen",
                "IrMedicaIdJM",
                "WCFK",
                "vv",
                "ALIL",
                "I_",
                "benefits",
                "SpouseI",
                "2900",
                "I19V0",
                "9d",
                "who",
                "EIN",
                "any",
                "From",
                "E",
                "PROVIDER",
                "_II_",
                "EPSOT",
                "QunLI",
                "27",
                "Include",
                "ADDITIONAL",
                "NameI",
                "AMPVA",
                "Oode",
                "L",
                "SI",
                "__",
                "I_Il_l",
                "r_I",
                "TELEPHCNE",
                "d",
                "PICA",
                "14",
                "ELIEE",
                "by",
                "the",
                "3",
                "Berkeley",
                "INFOaPH",
                "Phil",
                "99312",
                "INSURED",
                "Initial",
                "510",
                "OCR",
                "Street",
                "Designated",
                "12345",
                "DEGREES",
                "u",
                "Previous",
                "Circumstances",
                "26",
                "95",
                "500",
                "UNITS",
                "EErllly",
                "use",
                "his",
                "MMI",
                "OF",
                "my",
                "HA",
                "FEC",
                "COMPLETNG",
                "Ine",
                "BIRTH",
                "NATURE",
                "VJ",
                "ILLN",
                "FECA",
                "4A",
                "Fred",
                "BLK",
                "Mme",
                "I_I",
                "NUCC",
                "Part",
                "RELATICNSHIP",
                "POLICY",
                "b",
                "I_JI_I",
                "Area",
                "CURRENTIILLNESS",
                "THICAFIE",
                "17a",
                "ESS",
                "ICD",
                "MMIDDl",
                "DATE",
                "ZIP",
                "RESERVED",
                "Ind",
                "BILLING",
                "1970",
                "CITY",
                "Lu",
                "necessary",
                "SGNNG",
                "15",
                "_",
                "DIAGNOS",
                "NU",
                "ACCIDENT7",
                "authorize",
                "PRIOR",
                "_l",
                "PREGNANCY",
                "Z",
                "INFORMATION",
                "CONDITION",
                "L3A45678",
                "DDI",
                "OTHER",
                "IN",
                "9a",
                "that",
                "realest",
                "RESUEIMISSION",
                "UNABLEJYO",
                "Program",
                "reverse",
                "Inmall",
                "telow",
                "SEX",
                "eimer",
                "Flaw",
                "o3",
                "at",
                "Flrst",
                "29",
                "UV",
                "AP",
                "HOSPITALIZATICIN",
                "28",
                "94705",
                "T",
                "CURRENT",
                "PONTER",
                "bill",
                "13",
                "INJURY",
                "ILMPJ",
                "gnvemment",
                "Explain",
                "673633636",
                "PLANO",
                "IYINO",
                "24E",
                "PROCEDLFIES",
                "BEFORE",
                "CODE",
                "accepts",
                "DIAGNCSIS",
                "l_",
                "I",
                "MODIFIER",
                "Strangelove",
                "B",
                "32",
                "_DATEOP",
                "00",
                "BACK",
                "TEE",
                "SUPPLIER",
                "DATEIS",
                "2D",
                "also",
                "theunderglmed",
                "GROUP",
                "file",
                "19",
                "available",
                "ID",
                "FOR",
                "24",
                "Item",
                "234567",
                "HEALTH",
                "aPPytP",
                "Summer",
                "PATIENT",
                "PRINT",
                "SOURCE",
                "n",
                "this",
                "NAME",
                "_I",
                "OCEEELSHSSSQQIMENT",
                "CIT",
                "S",
                "N95",
                "0R",
                "SUPPLIES",
                "SSN",
                "MI",
                "17",
                "C",
                "Inwxoww",
                "AUTHCFIIZATICN",
                "of",
                "THIS",
                "I__l"
            ]
        },
        {
            "file_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/pages/7dfd171a-b5a6-4f25-b884-05a392b61d4b-2.png",
            "text_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/hocr/7dfd171a-b5a6-4f25-b884-05a392b61d4b-2.txt",
            "hocr_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/hocr/7dfd171a-b5a6-4f25-b884-05a392b61d4b-2.hocr",
            "page_no" : 2,
            "keywords" : [
                "U",
                "I3114",
                "1a",
                "Dl",
                "02",
                "Medical",
                "either",
                "St",
                "Last",
                "12",
                "c7",
                "PATIENTIS",
                "33407",
                "LUNG",
                "PROGRAM",
                "OEHER",
                "IYES",
                "JLX_I",
                "certify",
                "Spouselj",
                "100988M9N3",
                "4",
                "INO",
                "79007677727983",
                "TELEPHONE",
                "NPI",
                "Sheen",
                "made",
                "or",
                "YES",
                "AUTHORIZED",
                "services",
                "ACCIDENT",
                "described",
                "PLEASE",
                "st",
                "EPSDT",
                "ACCOUNT",
                "IXIYES",
                "Q",
                "CODES",
                "Kate",
                "c",
                "ORIGINAL",
                "APPROVED",
                "To",
                "A",
                "D",
                "r",
                "LAB",
                "see",
                "nucc",
                "statements",
                "583",
                "claim",
                "Middle",
                "omerl_l",
                "ml",
                "I_IYES",
                "OFrCURRENIl",
                "K",
                "RESUBMISSION",
                "UNABLEJQ",
                "F",
                "l_l",
                "PLAN",
                "NC",
                "West",
                "45th",
                "LI",
                "16",
                "AMOUNT",
                "TO",
                "wlI",
                "DAYS",
                "NUMBER",
                "government",
                "Relate",
                "30",
                "for",
                "FORM",
                "below",
                "8943",
                "thereof",
                "r6",
                "Manual",
                "Code",
                "MW",
                "QUALI",
                "AC",
                "Results",
                "MYES",
                "ASSIGNMENT",
                "PAID",
                "QUAL",
                "25",
                "7338",
                "Ianet",
                "i233897",
                "are",
                "TYPE",
                "2",
                "Use",
                "NATIONAL",
                "890785768",
                "Medicaid",
                "USE",
                "AUTO",
                "s",
                "RELATED",
                "IA",
                "Medicare",
                "PHYSICIAN",
                "18",
                "REF",
                "INSUREDIS",
                "I_l",
                "PERSONIS",
                "THERE",
                "myself",
                "1500",
                "CREDENTIALS",
                "www",
                "o",
                "I91",
                "Li",
                "H",
                "Center",
                "party",
                "MMi",
                "21",
                "TAX",
                "DVAVTE",
                "TOTAL",
                "660",
                "FACILITY",
                "BENEFIT",
                "Beach",
                "DATES",
                "IFOI",
                "Family",
                "ADDRESS",
                "10",
                "Lsi",
                "9",
                "Charles",
                "payment",
                "I31",
                "apply",
                "OCCUPATION",
                "ANOTHER",
                "MM",
                "LMP",
                "UNIFORM",
                "imiiii",
                "First",
                "l",
                "17a_",
                "11",
                "IDENT",
                "Hues",
                "MEDICAID",
                "I23",
                "45880387",
                "information",
                "BY",
                "No",
                "in",
                "ILXJ",
                "cnqul",
                "on",
                "READ",
                "NEI",
                "ACCEPT",
                "i_iNo",
                "to",
                "40",
                "OR",
                "g",
                "CHARGE",
                "MEDICARE",
                "United",
                "DL",
                "SIGNATURE",
                "IS",
                "Y",
                "service",
                "items",
                "EMG",
                "assignment",
                "1117",
                "Unusual",
                "J",
                "COMPLETING",
                "150",
                "6",
                "FROM",
                "SERVICES",
                "SERVICE",
                "Palm",
                "SIGNED",
                "Member",
                "DD",
                "CLAIM",
                "O",
                "31",
                "2201",
                "23",
                "W",
                "JFK",
                "INCLUDING",
                "Sunset",
                "INSURANCE",
                "pLACE",
                "complete",
                "0",
                "PROCEDURES",
                "and",
                "POINTER",
                "1",
                "IL",
                "org",
                "Plan",
                "a",
                "PLACE",
                "medical",
                "999876",
                "NRI",
                "LM8024N47QP3",
                "STATE",
                "REFERRING",
                "release",
                "Ml_l",
                "Instruction",
                "YY",
                "10d",
                "State",
                "T76",
                "INFO",
                "000",
                "78",
                "22",
                "L1I15I1",
                "ILLNESS",
                "RENDERING",
                "For",
                "45880398",
                "60",
                "20",
                "LIJ",
                "5",
                "G",
                "Health",
                "Name",
                "process",
                "7",
                "NO",
                "PERSONiS",
                "z",
                "561",
                "0L2",
                "T01I27I16",
                "EMPLOYMENT",
                "CHARGES",
                "86",
                "benefits",
                "9d",
                "who",
                "DATESleELATED",
                "EIN",
                "any",
                "RELATIONSHIP",
                "From",
                "E",
                "0938",
                "PROVIDER",
                "27",
                "Include",
                "ADDITIONAL",
                "line",
                "back",
                "L",
                "116",
                "Lang",
                "i27i17",
                "OUTSIDE",
                "d",
                "CPTlHCPCS",
                "medicai",
                "govt",
                "PICA",
                "14",
                "by",
                "the",
                "3",
                "INSURED",
                "Initial",
                "OCR",
                "Street",
                "Designated",
                "DEGREES",
                "u",
                "Previous",
                "Circumstances",
                "TRICARE",
                "CHAMPVA",
                "MMIDDI",
                "26",
                "30303",
                "UNITS",
                "_II_I",
                "DIAGNOSIS",
                "OF",
                "Fl_l",
                "11i15I171",
                "BIRTH",
                "NATURE",
                "INHURY",
                "FECA",
                "Blvd",
                "IVII_I",
                "WORK",
                "BEE",
                "BLK",
                "I_I",
                "NUCC",
                "_INO",
                "9006772983",
                "OMB",
                "POLICY",
                "b",
                "Area",
                "DATE",
                "ZIP",
                "RESERVED",
                "Mitchell",
                "BILLING",
                "Current",
                "78717321727735",
                "764321",
                "part",
                "claims",
                "CITY",
                "INSURANC",
                "1127i17",
                "33",
                "necessary",
                "FEDERAL",
                "31I47I",
                "15",
                "Al",
                "_",
                "1197",
                "authorize",
                "PRIOR",
                "_l",
                "4401",
                "Is",
                "PREGNANCY",
                "Z",
                "INFORMATION",
                "CONDITION",
                "OTHER",
                "uLAIM",
                "request",
                "IN",
                "undersigned",
                "9a",
                "that",
                "93",
                "50",
                "Program",
                "reverse",
                "I60",
                "Q1I15I171I27I17",
                "i",
                "SEX",
                "physician",
                "LOCATION",
                "899345",
                "Ifyes",
                "at",
                "L33",
                "other",
                "29",
                "11i",
                "LAII_I",
                "28",
                "90706777729837",
                "Lan",
                "ICDI",
                "HOSPITALIZATION",
                "T",
                "CURRENT",
                "PH",
                "Williams",
                "bill",
                "13",
                "suppiier",
                "03",
                "632",
                "IQ",
                "INJURY",
                "Explain",
                "300",
                "SIGNING",
                "24E",
                "MIS7I",
                "BEFORE",
                "CODE",
                "accepts",
                "I",
                "MODIFIER",
                "FL",
                "AUTHORIZATION",
                "B",
                "32",
                "BACK",
                "SUPPLIER",
                "FEE",
                "also",
                "GROUP",
                "19",
                "available",
                "ID",
                "FOR",
                "24",
                "Item",
                "oioo",
                "MDoD",
                "8",
                "HEALTH",
                "02l12",
                "42",
                "PATIENT",
                "Selim",
                "PRINT",
                "8P3",
                "SOURCE",
                "i15l16",
                "n",
                "WNO",
                "this",
                "NAME",
                "_I",
                "S",
                "SUPPLIES",
                "SSN",
                "17",
                "C",
                "Rsvd",
                "of",
                "THIS",
                "COMMITTEE"
            ]
        },
        {
            "file_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/pages/7dfd171a-b5a6-4f25-b884-05a392b61d4b-3.png",
            "text_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/hocr/7dfd171a-b5a6-4f25-b884-05a392b61d4b-3.txt",
            "hocr_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/hocr/7dfd171a-b5a6-4f25-b884-05a392b61d4b-3.hocr",
            "page_no" : 3,
            "keywords" : [
                "U",
                "1a",
                "FCR",
                "NEL",
                "St",
                "Stranglove",
                "SpouseI_I",
                "Claims",
                "Last",
                "INSUREJIS",
                "12",
                "PROGRAM",
                "y",
                "IYES",
                "muccorg",
                "4",
                "TELEPHONE",
                "6030",
                "NPI",
                "made",
                "JR",
                "KILLNESSl",
                "We",
                "or",
                "EiIhEr",
                "AUTHORIZED",
                "services",
                "ACCIDENT",
                "Holmes",
                "5551212",
                "PLEASE",
                "Indude",
                "RINO",
                "Regent",
                "EPSDT",
                "ACCOUNT",
                "I40",
                "LMF",
                "Q",
                "CFI",
                "c",
                "PERSON",
                "FLPEEIJF",
                "APPROVED",
                "inlcrman",
                "To",
                "A",
                "D",
                "r",
                "see",
                "statements",
                "AUTHCFIIZATION",
                "DATESYRELATED",
                "ul",
                "claim",
                "Middle",
                "q",
                "MICICIE",
                "III",
                "cerlify",
                "YI",
                "K",
                "RESUBMISSION",
                "HI",
                "F",
                "l_l",
                "CH",
                "3373533533",
                "an",
                "3mg",
                "PLAN",
                "mmplelre",
                "CPTI",
                "NINII",
                "16",
                "x",
                "DIAGNGSIS",
                "AMOUNT",
                "TO",
                "REAJEI",
                "tSIDW",
                "DAYS",
                "avaIIabIe",
                "NUMBER",
                "30",
                "for",
                "FORM",
                "below",
                "thereof",
                "LL",
                "Manual",
                "Code",
                "Results",
                "IYINOI",
                "PAID",
                "medlca",
                "25",
                "are",
                "TYPE",
                "2",
                "Use",
                "Ml",
                "NATIONAL",
                "12I25I16I12I25I16I11I",
                "USE",
                "AUTO",
                "desalted",
                "RELATED",
                "IOM",
                "PHYSICIAN",
                "REF",
                "I_l",
                "THERE",
                "myself",
                "CREDENTIALS",
                "www",
                "mysidan",
                "CA",
                "H",
                "party",
                "__n",
                "21",
                "1212",
                "TOTAL",
                "FACILITY",
                "BENEFIT",
                "DATES",
                "m",
                "CFIIGINAL",
                "Family",
                "g1",
                "UNIFOFIM",
                "Eves",
                "ADDRESS",
                "marl",
                "10",
                "9",
                "agelgnmem",
                "payment",
                "CF",
                "I3",
                "OCCUPATION",
                "ANOTHER",
                "MM",
                "l",
                "First",
                "11",
                "MEDICAID",
                "Relale",
                "FUT_",
                "l_rl_I",
                "FEDERALTAX",
                "BY",
                "in",
                "Fl",
                "_L",
                "GROJP",
                "on",
                "READ",
                "1030003",
                "to",
                "Ihe",
                "40",
                "OR",
                "well",
                "g",
                "SENNG",
                "CHARGE",
                "MEDICARE",
                "DIAGNCBIS",
                "SIGNATURE",
                "IS",
                "Y",
                "items",
                "EMG",
                "7900",
                "e",
                "L_II_",
                "UNABLEJP",
                "Unusual",
                "53",
                "6",
                "SERVICES",
                "ULAIM",
                "SERVICE",
                "OUALI",
                "555",
                "SIGNED",
                "OJTSIDELAB",
                "DD",
                "CLAIM",
                "O",
                "31",
                "CR",
                "IX",
                "23",
                "INCLUDING",
                "INSURANCE",
                "JYES",
                "1770638030",
                "0",
                "PROCEDURES",
                "and",
                "1",
                "II",
                "PRCIERAM",
                "Plan",
                "a",
                "PLACE",
                "medical",
                "ii",
                "release",
                "REFERRING",
                "STATE",
                "Instruction",
                "INFO",
                "YY",
                "10d",
                "_d",
                "Main",
                "NLICC",
                "22",
                "ILLNESS",
                "RENDERING",
                "For",
                "20",
                "mnems",
                "Eli",
                "123",
                "5",
                "r_l",
                "G",
                "1234567",
                "Dr",
                "Name",
                "777663",
                "process",
                "Dealgnated",
                "El",
                "7",
                "NO",
                "94704",
                "EMPLOYMENT",
                "CHARGES",
                "In",
                "ALIL",
                "rquesl",
                "I_",
                "IrMedacam",
                "2900",
                "9d",
                "who",
                "IL3A45678",
                "EIN",
                "any",
                "RELATIONSHIP",
                "From",
                "E",
                "PROVIDER",
                "tenelits",
                "jaw",
                "27",
                "I03",
                "ADDITIONAL",
                "AMPVA",
                "L1",
                "L",
                "TFIICAFIE",
                "SI",
                "CCDES",
                "__",
                "lndude",
                "CURRENI",
                "IONI",
                "d",
                "ACCEPTASSIGNMENT",
                "PICA",
                "14",
                "3",
                "by",
                "the",
                "Berkeley",
                "Phil",
                "99312",
                "510",
                "INSURED",
                "Initial",
                "OCR",
                "Street",
                "Designated",
                "12345",
                "DEGREES",
                "u",
                "Previous",
                "MMIDDI",
                "26",
                "low",
                "95",
                "Slgnature",
                "r_",
                "his",
                "MMI",
                "OF",
                "my",
                "COMPLETNG",
                "BIRTH",
                "NATURE",
                "L_I",
                "FECA",
                "Fred",
                "IL_I",
                "paymentm",
                "WORK",
                "I_I",
                "UerS",
                "I__I",
                "NUCC",
                "POLICY",
                "b",
                "Area",
                "ICD",
                "DATE",
                "ZIP",
                "ooI",
                "he",
                "PHI",
                "RESERVED",
                "Ind",
                "BILLING",
                "part",
                "1970",
                "CITY",
                "02312",
                "Cf",
                "33",
                "necessary",
                "15",
                "app",
                "_",
                "gnvernment",
                "authorize",
                "PRIOR",
                "_l",
                "PREGNANCY",
                "lhe",
                "Z",
                "INFORMATION",
                "CONDITION",
                "I_1",
                "DDI",
                "DI",
                "OTHER",
                "IN",
                "undersigned",
                "9a",
                "that",
                "lalsn",
                "OIherI",
                "reverse",
                "DVAITE",
                "Program",
                "i",
                "Inilial",
                "SEX",
                "Nu",
                "LOCATION",
                "Ifyes",
                "at",
                "RI",
                "other",
                "29",
                "28",
                "94705",
                "111I19",
                "tall",
                "HOSPITALIZATION",
                "T",
                "CURRENT",
                "PONTER",
                "13",
                "03",
                "SU",
                "1I",
                "INJURY",
                "Explain",
                "HCPCS",
                "IYINO",
                "24E",
                "BEFORE",
                "MMl",
                "CODE",
                "accepts",
                "l_",
                "I",
                "MODIFIER",
                "Strangelove",
                "B",
                "Orwmstances",
                "32",
                "00",
                "BACK",
                "___l",
                "SUPPLIER",
                "155",
                "INSURANUI",
                "GROUP",
                "file",
                "19",
                "ID",
                "FOR",
                "24",
                "Item",
                "8",
                "HEALTH",
                "IAI",
                "PATIENT",
                "vnl",
                "173",
                "Selim",
                "PRINT",
                "SOURCE",
                "n",
                "NAME",
                "IfMedrcareJJI",
                "_I",
                "CIT",
                "S",
                "N95",
                "tam",
                "PT",
                "BfRTUNG",
                "MI",
                "SUPPLIES",
                "SSN",
                "Ives",
                "fMemberIDaf",
                "17",
                "C",
                "lne",
                "Jr",
                "OUAL",
                "Rsvd",
                "OJrrent",
                "THIS",
                "COMMITTEE"
            ]
        }
    ],
    "file_name" : "multi _skew",
    "extn" : "pdf",
    "doc_state" : "ready",
    "template_name" : "multiskew",
    "created_ts" : "2018-05-25T14:04:12.870486",
    "no_of_pages" : 3,
    "updated_ts" : "2018-06-25T10:25:10.603803",
    "file_path" : "ranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7/templates/da6ea606-aed0-4aeb-ab13-fcf363fb7c4e/7dfd171a-b5a6-4f25-b884-05a392b61d4b.pdf",
    "is_deleted" : False,
    "thresholds" : {
        "post_processing" : {
            "document_threshold" : 40,
            "entity_confidence_score" : 50
        },
        "extraction" : {
            "document_threshold" : 80,
            "entity_confidence_score" : 70
        },
        "annotation" : {
            "document_threshold" : 60,
            "entity_confidence_score" :80
        },
        "page_classification" : {
            "document_threshold" : 90,
            "entity_confidence_score" : 90
        }
    }
}



map_data = {
    "solution_id" : "aranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7",
    "template_id" : "a629ac584-7afe-43c6-935c-507d76632dd3",
    "updated_ts" : "2018-04-18T16:17:02.894391",
    "created_ts" : "2018-04-09T16:17:23.073248",
    "sections" : {
        "default" : {
            "elements" : {
                "5189ce86-8b94-466a-b016-d4c455eed527" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.sex",
                    "doc_var" : None
                },
                "7a634dbf-fdf9-4b13-8904-29ce6cf315aa" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.other_claim_id",
                    "doc_var" : None
                },
                "13d5aef7-e2bb-41f0-8f3a-4f73be76881b" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Services.billing_provider_npi",
                    "doc_var" : None
                },
                "2d2c71a0-2a99-4606-b222-29217956da5b" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.birth_date_dd",
                    "doc_var" : None
                },
                "5f4f71a8-8310-4287-9ab9-5ce383b7de75" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.telephone",
                    "doc_var" : None
                },
                "d67fe143-d0df-49a1-b3fe-6212ddb91a87" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.accept_assignment",
                    "doc_var" : None
                },
                "41d5328e-66b4-42bf-8c57-61092a796bdd" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.other_date_dd",
                    "doc_var" : None
                },
                "b9bd3107-7952-43cc-9ac5-7358c46c2344" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.other_date_mm",
                    "doc_var" : None
                },
                "10268212-baea-4957-b8d9-11c3c53fd6b9" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.reserved_for_nucc",
                    "doc_var" : None
                },
                "a91ea5eb-fdbd-4a59-bceb-584f5580722a" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.account_no",
                    "doc_var" : None
                },
                "a9dfe19d-5df3-426e-81ef-dec17cf23650" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Services.facility_location_id",
                    "doc_var" : None
                },
                "5c264f3a-2260-485a-9ea2-720826d58bbe" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.birth_date_yy",
                    "doc_var" : None
                },
                "eb051951-b816-44dd-9222-1feddcb8474a" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.name",
                    "doc_var" : None
                },
                "eeca8e6f-5c52-4ac4-ad71-f09da85c336d" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.federal_tax_type",
                    "doc_var" : None
                },
                "c593e54d-6fe6-4193-9352-339865c09dec" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.other_insured_name",
                    "doc_var" : None
                },
                "9c14ae5a-fd1b-4751-863a-01a530a4af57" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.date_of_current_illness_mm",
                    "doc_var" : None
                },
                "715d8bb1-d81e-47ae-946d-77f4287f7107" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.state",
                    "doc_var" : None
                },
                "c8061289-8418-45d6-b44c-6319a77fd2b7" : {
                    "is_deleted" : False,
                    "is_doc_var" : True,
                    "map_to" : "state_patient",
                    "doc_var" : {
                        "rule_id" : [

                        ],
                        "name" : "state_patient",
                        "type" : "string"
                    }
                },
                "e6668b48-d19d-4e1f-8b6c-56ed52a9a379" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.city",
                    "doc_var" : None
                },
                "a8706aaf-d153-475b-abf8-1450a29860dd" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.date_of_current_illness_dd",
                    "doc_var" : None
                },
                "0d2a4389-070b-4b3a-92cb-4b77017c20a6" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.relationship_to_insured",
                    "doc_var" : None
                },
                "40d360a2-afc9-4f9b-b931-e91f504b7a13" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.address",
                    "doc_var" : None
                },
                "0cd9d9b1-f797-4e92-a4e9-84deb8f401df" : {
                    "is_deleted" : True,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.federal_tax_type",
                    "doc_var" : None
                },
                "8f1dbd73-52d6-43d9-ba86-d5ffa531a1b8" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.employment",
                    "doc_var" : None
                },
                "6d1a3441-7b1a-4b29-a0f8-407cb44ef778" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.date_of_current_illness_yy",
                    "doc_var" : None
                },
                "ba0347dc-3b5a-41bd-a7ca-e0cdd44f820b" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.telephone",
                    "doc_var" : None
                },
                "4790662b-ee31-4737-94c5-af887da615fb" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.insurance_plan_name",
                    "doc_var" : None
                },
                "efe9d341-8dfb-458a-8ebd-e26c5bb177d8" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.total_charge",
                    "doc_var" : None
                },
                "2e875001-dfe5-412a-b6d3-ed54f9ae13de" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.insured_id_number",
                    "doc_var" : None
                },
                "900db22b-70b8-47a8-b4c1-ade1cdf33958" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.another_health_benefit_plan",
                    "doc_var" : None
                },
                "8cf71f97-23c8-4d82-aa93-7e4159770f85" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.birth_date_yy",
                    "doc_var" : None
                },
                "f03e94df-4ff5-4568-a260-cb8d64469801" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.claims_code",
                    "doc_var" : None
                },
                "efb2b4f8-8869-4696-9c19-f6b96e0227af" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.signature_of_physician",
                    "doc_var" : None
                },
                "449767ee-7b3a-4d27-8be8-7d749780ac6d" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.zip_code",
                    "doc_var" : None
                },
                "9ec837ab-5d46-4c6c-8035-795bb365d013" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.address",
                    "doc_var" : None
                },
                "dc0fe4f3-aacd-4445-9c8d-04d4b05e0550" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.other_date_yy",
                    "doc_var" : None
                },
                "a8cb8e00-9200-4d17-9e9c-ea812280afbc" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.other_insured_policy",
                    "doc_var" : None
                },
                "d40fdfee-777a-412a-b24f-3bd6b0cc246d" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Services.billing_provider_phn",
                    "doc_var" : None
                },
                "b9fccafe-8e35-407a-b27f-73036d18b4b6" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.other_accident",
                    "doc_var" : None
                },
                "770cf468-6525-4187-9437-a53626d3f4f3" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.sex",
                    "doc_var" : None
                },
                "db98c3b1-f644-46c3-ac1f-fa54f7cb6f60" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.birth_date_dd",
                    "doc_var" : None
                },
                "6a099921-73fa-42bd-aed5-63a12e8dbbff" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.federal_tax_id_number",
                    "doc_var" : None
                },
                "c51c9bcb-86f4-4fb6-a6d9-c5512c523192" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Services.facility_location",
                    "doc_var" : None
                },
                "c432c80b-7970-4584-997a-5d2717e9b881" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.9b_reserved_for_nucc",
                    "doc_var" : None
                },
                "c65a7fe8-ee2a-49ea-b41d-2c0f272ede0f" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.city",
                    "doc_var" : None
                },
                "0648de6d-ebb9-4523-a8f1-ebbef1ba6cb4" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Services.billing_provider_info",
                    "doc_var" : None
                },
                "bd7afa05-2f73-4cfa-b0f5-a52c86c2c9c5" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.name",
                    "doc_var" : None
                },
                "9533858c-db50-4edc-a795-42c3d85899cf" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Services.billing_provider_id",
                    "doc_var" : None
                },
                "3118cbbd-cc51-4988-8110-d8276d49bf79" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Services.facility_location_npi",
                    "doc_var" : None
                },
                "d2eeec63-26a2-4f3d-8329-fce495f5c940" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.insurance_type",
                    "doc_var" : None
                },
                "95444bc6-906e-4452-a028-38da5ee361d8" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.9d_insurance_plan_name",
                    "doc_var" : None
                },
                "9c2152c9-5dd5-466f-8881-5f33c7a6b3cc" : {
                    "is_deleted" : False,
                    "is_doc_var" : True,
                    "map_to" : "zipcode_patient",
                    "doc_var" : {
                        "rule_id" : [

                        ],
                        "name" : "zipcode_patient",
                        "type" : "numeric"
                    }
                },
                "d49cd09d-7e86-43f5-b35e-174d68bc6d6a" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.other_accident",
                    "doc_var" : None
                },
                "60be86d8-851f-4547-adaa-271f56832ee0" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.birth_date_mm",
                    "doc_var" : None
                },
                "05234f45-1edd-4cbd-837d-416c0457a730" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Patient.birth_date_mm",
                    "doc_var" : None
                },
                "f070fc22-bad6-46cd-b0d5-8df5a627c857" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.Insured.policy_group",
                    "doc_var" : None
                },
                "863f27d5-d55d-4780-bb71-814b4f31865b" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.amount_paid",
                    "doc_var" : None
                },
                "39070457-edd4-407b-a5d7-6e98d7bc0e21" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.reserved_for_nucc",
                    "doc_var" : None
                },
                "1b087791-4939-487a-8562-eb60b9aa9582" : {
                    "is_deleted" : False,
                    "is_doc_var" : False,
                    "map_to" : "Claim.other_details.9c_reserved_for_nucc",
                    "doc_var" : None
                }
            }
        }
    },
    "section_id" : "default"
}


json1 = {
  "doc_id": "afe2d978a-0f6a-4844-b872-812222764908",
  "element_id": "ad93ca82-510e-4b7e-a764-1f651ae26a92",
  "section_id": "default",
  "solution_id": "aranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7",
  "type": "table",
  "table_name": "table_1",
  "columns": [
    {
      "column_no": 0,
      "value": [
        {
          "line": 0,
          "text": "1"
        },
        {
          "line": 1,
          "text": "2"
        },
        {
          "line": 2,
          "text": "3"
        },
        {
          "line": 3,
          "text": "4"
        },
        {
          "line": 4,
          "text": "5"
        },
        {
          "line": 5,
          "text": "6"
        },
        {
          "line": 6,
          "text": "7"
        },
        {
          "line": 7,
          "text": "8"
        },
        {
          "line": 8,
          "text": "9"
        },
        {
          "line": 9,
          "text": "10"
        },
        {
          "line": 10,
          "text": "11"
        },
        {
          "line": 11,
          "text": "12"
        }
      ],
      "name": "Sl No."
    },
    {
      "column_no": 1,
      "value": [
        {
          "line": 0,
          "text": "01 Jan 2018"
        },
        {
          "line": 1,
          "text": "15 Jan 2018"
        },
        {
          "line": 2,
          "text": "26 Jan 2018"
        },
        {
          "line": 3,
          "text": "02 Mar 2018"
        },
        {
          "line": 4,
          "text": "19 Mar 2018"
        },
        {
          "line": 5,
          "text": "15 Aug 2018"
        },
        {
          "line": 6,
          "text": "13 Sep 2018"
        },
        {
          "line": 7,
          "text": "02 Oct 2018"
        },
        {
          "line": 8,
          "text": "19 Oct 2018"
        },
        {
          "line": 9,
          "text": "05 Nov 2018"
        },
        {
          "line": 10,
          "text": "06 Nov 2018"
        },
        {
          "line": 11,
          "text": "25 Dec 2018"
        }
      ],
      "name": "Date"
    },
    {
      "column_no": 2,
      "value": [
        {
          "line": 0,
          "text": "New Year"
        },
        {
          "line": 1,
          "text": "Sankranti"
        },
        {
          "line": 2,
          "text": "Republic Day"
        },
        {
          "line": 3,
          "text": "Holi"
        },
        {
          "line": 4,
          "text": "Ugadi"
        },
        {
          "line": 5,
          "text": "Independence Day"
        },
        {
          "line": 6,
          "text": "Ganesh Chaturti"
        },
        {
          "line": 7,
          "text": "Gandhi Jayanti"
        },
        {
          "line": 8,
          "text": "Dussehra"
        },
        {
          "line": 9,
          "text": "Diwali"
        },
        {
          "line": 10,
          "text": "Diwali"
        },
        {
          "line": 11,
          "text": "Christmas"
        }
      ],
      "name": "Holiday"
    },
    {
      "column_no": 3,
      "value": [
        {
          "line": 0,
          "text": "General"
        },
        {
          "line": 1,
          "text": "General"
        },
        {
          "line": 2,
          "text": "General"
        },
        {
          "line": 3,
          "text": "General"
        },
        {
          "line": 4,
          "text": "General"
        },
        {
          "line": 5,
          "text": "General"
        },
        {
          "line": 6,
          "text": "General"
        },
        {
          "line": 7,
          "text": "General"
        },
        {
          "line": 8,
          "text": "General"
        },
        {
          "line": 9,
          "text": "General"
        },
        {
          "line": 10,
          "text": "General"
        },
        {
          "line": 11,
          "text": "General"
        }
      ],
      "name": "Holiday Type"
    }
  ],
  "updated_ts": "2018-06-26T12:50:16.587648",
  "headings": [
    {
      "column_no": 0,
      "column": [
        "Sl No."
      ]
    },
    {
      "column_no": 1,
      "column": [
        "Date"
      ]
    },
    {
      "column_no": 2,
      "column": [
        "Holiday"
      ]
    },
    {
      "column_no": 3,
      "column": [
        "Holiday Type"
      ]
    }
  ],
  "created_ts": "2018-06-26T12:50:16.587657",
  "page_no": 1
}


page = {
    "children": [],
    "doc_id": "86645a0d-aa08-41ba-9e08-52a136fe4ef4",
    "is_root": False,
    "is_test": True,
    "doc_state":"processed",
    "metadata": {
        "properties": {
            "extension": ".png",
            "file_resource": {
                "bucket": None,
                "key": "unit_test_solution/documents/86645a0d-aa08-41ba-9e08-52a136fe4ef4/test.png-000.png",
                "storage": "efs"
            },
            "filename": "test.png-000.png",
            "num_pages": 0,
            "pdf_resource": {
                "bucket": None,
                "key": None,
                "storage": "efs"
            },
            "size": 204854
        },
        "template_info": {
            "id": "",
            "name": "",
            "score": 0
        }
    },
    "pages": [{
        "metadata": {
            "raw": {
                "bucket": None,
                "key": "unit_test_solution/documents/86645a0d-aa08-41ba-9e08-52a136fe4ef4/pages/test.png-000.png",
                "storage": "efs"
            },
            "deskew": {
                "bucket": None,
                "key": "unit_test_solution/documents/86645a0d-aa08-41ba-9e08-52a136fe4ef4/pages/preprocess-test.png-000.png",
                "storage": "efs"
            },
            "hocr": {
                "bucket": None,
                "key": "unit_test_solution/documents/86645a0d-aa08-41ba-9e08-52a136fe4ef4/pages/test.png-000.hocr",
                "storage": "efs"
            }
        },
        "num": 1
    }],
    "parent_id": "7314ad35-d726-461c-b7b4-4ad4c94349f4",
    "processing_state": "convert_complete",
    "solution_id": "unit_test_solution",
    "elements": [{
        "id": "uuid1",
        "type": "section",
        "coordinates": [{
            "top_right": 100,
            "top_left": "50",
            "bottom_left": 100,
            "bottom_right": 200,
            "page_number": 1
        }],
        "confidence": 80,
        "is_deleted": False,
        "insight_id": "uuid2",
        "parameters": {},
        "elements": [{
                "id": "uuid3",
                "type": "fields",
                "coordinates": [{
                    "top_right": 100,
                    "top_left": 50,
                    "bottom_left": 100,
                    "bottom_right": 200,
                    "page_number": 1
                }],
                "confidence": 80,
                "is_deleted": False,
                "insight_id": "uuid4",
                "parameters": {
                    "label": "Name",
                    "text": "ENSO",
                    "label_coordinates": [{
                        "top_right": 100,
                        "top_left": "50",
                        "bottom_left": 100,
                        "bottom_right": 200,
                        "page_number": 1
                    }],
                    "has_label": True
                }
            },
            {
                "id": "uuid5",
                "type": "sentences",
                "coordinates": [{
                    "top_right": 100,
                    "top_left": 50,
                    "bottom_left": 100,
                    "bottom_right": 200,
                    "page_number": 1
                }],
                "confidence": 80,
                "is_deleted": False,
                "insight_id": "uuid6",
                "parameters": {
                    "text": "ENSO is XPMS Platform",
                    "text_list": ["ENSO", "is", "XPMS", "Platform"]
                }
            },
            {
                "id": "uuid7",
                "type": "table",
                "coordinates": [{
                    "top_right": 100,
                    "top_left": 50,
                    "bottom_left": 100,
                    "bottom_right": 200,
                    "page_number": 1
                }],
                "confidence": 80,
                "is_deleted": False,
                "insight_id": "uuid8",
                "parameters": {
                    "columns": [{
                        "seq_no": 1,
                        "name": "S.No",
                        "insight_id": "uuid9",
                        "rows": [{
                            "text": "1",
                            "coordinates": [{
                                "top_right": 100,
                                "top_left": 50,
                                "bottom_left": 100,
                                "bottom_right": 200,
                                "page_number": 1
                            }],
                            "confidence": 90,
                            "row_no": 1
                        }]
                    }]
                }
            }
        ]
    }]
}

columns=[{
                        "seq_no": 1,
                        "name": "S.No",
                        "insight_id": "uuid9",
                        "rows": [{
                            "text": "1",
                            "coordinates": [{
                                "top_right": 100,
                                "top_left": 50,
                                "bottom_left": 100,
                                "bottom_right": 200,
                                "page_number": 1
                            }],
                            "confidence": 90,
                            "row_no": 1
                        }]
                    }]

feedbacklist = {}

headings = [{'insight_id': '11dbf529-492b-42a1-a391-b3332359b53a', 'column_no': 0, 'column': ['Salt', 'Concetration', '(%)']},
{'insight_id': '0d7190b5-5074-4d00-bae3-d188fa1073e8', 'subColumn': [['Trail #1']], 'column_no': 1, 'column': ['Tranmittance(%T)']}]

@pytest.mark.run(order=1)
def insert_temp(temp):
    MongoDbConn.insert(TEMPLATE_COLLECTION, temp)
    return temp['solution_id']


def get_temp(solution_id=None):
    query = {"solution_id": solution_id}
    temp_data = MongoDbConn.find_one(TEMPLATE_COLLECTION, query)
    return temp_data

get_temp(solution_id="aranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7")


@pytest.mark.run(order=1)
def insert_map(map_data = None):
    MongoDbConn.insert(MAPPING_COLLECTION, map_data)
    return map_data['solution_id']


def get_mapdb(solution_id=None):
    query = {"solution_id": solution_id}
    mapdata = MongoDbConn.find_one(MAPPING_COLLECTION, query)
    return mapdata

get_mapdb(solution_id="aranger1_5f2a66b5-382a-4a37-8161-01a7491a06a7")

@pytest.mark.run(order=2)
def insert_db(json1):
    MongoDbConn.insert(DOC_ELEMENTS_COLLECTION, json1)
    return json1['doc_id']


def get_db(doc_id=None):
    query = {"doc_id": doc_id}
    data = MongoDbConn.find_one(DOC_ELEMENTS_COLLECTION, query)
    return data

get_db(doc_id="afe2d978a-0f6a-4844-b872-812222764908")


@pytest.mark.run(order=3)
def page_db(page):
    MongoDbConn.insert(DOCUMENTS_COLLECTION, page)
    return page['doc_id']


def get_doc_db(doc_id=None):
    query = {"doc_id": doc_id}
    page_data = MongoDbConn.find_one(DOCUMENTS_COLLECTION, query)
    print(page_data)
    return page_data

get_doc_db(doc_id="afe2d978a-0f6a-4844-b872-812222764908")
