# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-11 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S3Bucket',
        ),
        migrations.RemoveField(
            model_name='solutionuser',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solutionuser',
            name='solution_user',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='SolutionUser',
        ),
    ]
