"""
Django settings for console project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

if os.environ['DJANGO_ENV'] == "prod":
    from console.prod_settings import *
elif os.environ['DJANGO_ENV'] == "dev":
    from console.dev_settings import *
